package com.fbs.datasource;

import javax.sql.DataSource;

import org.springframework.beans.factory.InitializingBean;
import org.springframework.jdbc.core.JdbcTemplate;

public class ItemDataPopulator implements InitializingBean
{
	private static final String CREATE_TABLES = "create table Item (\n"
	        + "    id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1)PRIMARY KEY,"
	        + "    name varchar(255),\n" + "    price double not null\n" + ");";
	protected boolean createSchema = true;
	protected DataSource dataSource = null;
	protected String tenantId;


	public void setCreateSchema(boolean createSchema)
	{
		this.createSchema = createSchema;
	}

	public void setClient(String tenantId)
	{
		this.tenantId = tenantId;
	}


	public void setDataSource(DataSource dataSource)
	{
		this.dataSource = dataSource;
	}


	@Override
	public void afterPropertiesSet()
	{
		// because we're using an in-memory hsqldb for the sample app, a new one
		// will be created each time the
		// app starts, so create the tables and insert the 2 sample users on
		// bootstrap:

		JdbcTemplate jdbcTemplate = new JdbcTemplate(this.dataSource);

		if (createSchema)
		{
			jdbcTemplate.execute(CREATE_TABLES);
		}

		String name = "Item for tenant " + this.tenantId;
		String query = "insert into Item values ('1', '" + name + "', '1' )";

		jdbcTemplate.execute(query);
	}

}
